const categories = [
    {category:'ARTIST - SONG TITLE',words:[
        'ASHER ROTH - I LOVE COLLEGE',
        "CHIEF KEEF - I DON'T LIKE",
        'DEMONDICE - SNAKE EYES',
        'ELLIE GOULDING - LIGHTS',
        'FIVIO FOREIGN - PLAQUEBOYMAX', 
        'FUTURE - FUCK UP SOME COMMAS',
        'JASON DERULO - WIGGLE',
        'KAI CENAT - BUSTDOWN ROLLIE AVALANCHE',
        'KENDRICK LAMAR - MONEY TREES',
        'KENDRICK LAMAR - NOT LIKE US',
        'LIL YACHTY - POLAND',
        'MICHAEL JACKSON - THRILLER',
        'MICHAEL JACKSON - ROCK WITH YOU',
        'NAV - BALLER',
        'NBA YOUNGBOY - MAKE NO SENSE',
        'NETTSPEND - NOTHING LIKE UUU',
        'NLE CHOPPA - SHOTTA FLOW',
        "OINGO BOINGO - DEAD MAN'S PARTY",
        'SOULJA BOY - KISS ME THRU THE PHONE',
        'TRAVIS SCOTT - GOOSEBUMPS',
        'XAVIERSOBASED - CRISP DUBS',
    ]},

    {category:'BOGO MEMBERS',words:[
        'ADRIEL MOTTER', 
        'ALEX WALTER', 
        'ANDE CHRISTENSON', 
        'CHRIS BEHARRY', 
        'JESSE MERRELL',
        'KENNY FERGERSON',
        'RILEY TRACY'
    ]},

    {category:'FLASH GAMES',words:[
        'ACHIEVEMENT UNLOCKED',
        'ALIEN HOMINID',
        'BAD ICE CREAM',
        'BEJEWELED',
        'BLOONS TOWER DEFENSE',
        'BLOXORZ',
        'BOWMAN',
        'BUBBLE TANKS',
        'CANABALT',
        'CIVIBALLS',
        'CLUB PENGUIN',
        'CRUSH THE CASTLE',
        'CUBE DROID SAVES THE GALAXY',
        'DOEO',
        "DON'T SHIT YOUR PANTS",
        'DUCK LIFE',
        'ELECTRIC MAN',
        'EPIC COMBO REDUX',
        'EXIT PATH',
        'EXTREME PAMPLONA',
        'FACTORY BALLS',
        'FARFALLE',
        'FIREBOY AND WATERGIRL',
        'FRACUUM',
        'GRAVITY GUY',
        'HAPPY WHEELS',
        'HENRY STICKMIN',
        'HOSHI SAGA',
        'I SAW HER STANDING THERE',
        'INTERACTIVE BUDDY',
        'IQ BALL',
        'JELLY ESCAPE',
        'JOHNNY UPGRADE',
        'LEARN TO FLY',
        'LINE RIDER',
        'ME AND THE KEY',
        'MEAT BOY',
        'MUTINY',
        'NINJA PAINTER',
        'NITROME MUST DIE',
        "PAPA'S FREEZERIA",
        'PETPET PARK',
        "PICO'S SCHOOL",
        'PLANTS VS ZOMBIES',
        'POPTROPICA',
        'QWOP',
        'RAFT WARS',
        'RED BALL',
        'RIDDLE SCHOOL',
        'RUBBLE TROUBLE',
        'RUN',
        'SIXTY SECOND BURGER RUN',
        'SLAP THE MONKEY',
        'SUGAR, SUGAR',
        'SUSHI CAT',
        'THE FANCY PANTS ADVENTURES',
        'THE I OF IT',
        'THE IMPOSSIBLE QUIZ',
        "THE WORLD'S HARDEST GAME",
        'THIS IS THE ONLY LEVEL',
        'VAMPIRE SKILLS',
        'WHACK YOUR BOSS',
        'WONDERPUTT',
    ]},

    {category:'FLORIDA COUNTIES', words:[
        'BROWARD',
        'CLAY',
        'DUVAL',
        'HILLSBORO',
        'LAKE',
        'MIAMI-DADE',
        'OKALOOSA',
        'ORANGE',
        'PINELLAS',
        'POLK',
        'SEMINOLE',
        'SUWANEE',
        'VOLUSIA',
    ]},

    {category:'PHRASES',words:[
        "DON'T PISS ON MY BACK AND TELL ME IT'S RAININ'",
        'GOD DAMN, GET OFF MY DEEZLY',
        'HELL OR HIGH WATER',
        'I COULD MAKE YOU FAMOUS ON INSTAGRAM',
        'SLOWER THAN MOLASSES IN JANUARY',
    ]},

    {category:'TYPES OF APPLE',words:[
        'FUJI',
        'GALA',
        'GOLDEN DELICIOUS',
        'GRANNY SMITH',
        'HONEYCRISP',
        'PINK LADY',
        'MACINTOSH',
        'RED DELICIOUS',
    ]},

    {category:'VIDEO GAMES',words:[
        'BOOGERMAN',
        'DARK SOULS',
        'ELDEN RING',
        'LEISURE SUIT LARRY',
        'MINECRAFT',
        'SUPER MARIO WORLD',
    ]},

    {category:'ROBLOX GAMES',words:[
        'ARSENAL',
        'BEE SWARM SIMULATOR',
        'CLEANING SIMULATOR',
        'DOOMSPIRE BRICKBATTLE',
        'DRESS TO IMPRESS',
        'ESCAPE AREA FIFTY ONE',
        'GROW A GARDEN',
        'MURDER MYSTERY',
        'NATURAL DISASTER SURVIVAL',
        'PHANTOM FORCES',
        'STOP IT SLENDER',
        'WELCOME TO BLOXBURG',
    ]}
];